from __future__ import annotations

from typing import Any

from nereus.agents.base import BaseAgent
from nereus.core.state import (
    LearningStatus,
    NereusState,
    Roadmap,
    RoadmapTopic,
    UserProfile,
)
from nereus.llm.schema import extract_json


class CoachAgent(BaseAgent):
    """Coach Agent.

    Collects the user's skill, goals and constraints into a ``UserProfile``
    and builds a ``Roadmap`` of topics. When an LLM provider is available the
    roadmap is generated by the model; otherwise a deterministic stub roadmap
    is used so the automaton keeps working offline.
    """

    def __init__(self, provider=None) -> None:
        self._provider = provider

    # ------------------------------------------------------------------ #
    # Deterministic fallback
    # ------------------------------------------------------------------ #
    def build_roadmap(self, profile: UserProfile) -> Roadmap:
        topics = [
            RoadmapTopic(
                id="1",
                title=f"{profile.skill}: fundamentals",
                description="Core concepts and terminology.",
            ),
            RoadmapTopic(
                id="2",
                title=f"{profile.skill}: practice",
                description="Hands-on exercises and applied tasks.",
            ),
            RoadmapTopic(
                id="3",
                title=f"{profile.skill}: advanced",
                description="Advanced topics and best practices.",
            ),
        ]
        return Roadmap(topics=topics)

    # ------------------------------------------------------------------ #
    # LLM-backed roadmap
    # ------------------------------------------------------------------ #
    def _prompt(self, profile: UserProfile) -> list[dict[str, Any]]:
        return [
            {
                "role": "system",
                "content": (
                    "You are an expert learning coach. Build a personalized learning "
                    "roadmap for the user. Return ONLY valid JSON with key "
                    '"topics": [{"id": "<1-based string>", "title": "<str>", '
                    '"description": "<str>"}, ...] with 5 to 8 topics ordered from '
                    "fundamentals to advanced."
                ),
            },
            {
                "role": "user",
                "content": (
                    f"Skill: {profile.skill}\n"
                    f"Current level: {profile.current_level.value}\n"
                    f"Target level: {profile.target_level.value}\n"
                    f"Hours per day: {profile.hours_per_day}\n"
                    f"Deadline: {profile.deadline_days} days\n"
                    f"Goal: {profile.goal}"
                ),
            },
        ]

    def build_roadmap_llm(self, profile: UserProfile) -> Roadmap:
        if self._provider is None:
            return self.build_roadmap(profile)
        try:
            raw = self._provider.complete(
                self._prompt(profile), temperature=0.4, json_mode=True
            )
            data = extract_json(raw)
            topics = data["topics"]
            return Roadmap(
                topics=[RoadmapTopic(**topic) for topic in topics],
            )
        except Exception:
            return self.build_roadmap(profile)

    # ------------------------------------------------------------------ #
    # Agent interface
    # ------------------------------------------------------------------ #
    def run(self, state: NereusState) -> dict:
        profile = state["user_profile"]
        if profile is None:
            raise ValueError("CoachAgent requires a user_profile in state")

        roadmap = self.build_roadmap_llm(profile)

        return {
            "roadmap": roadmap,
            "current_topic_index": 0,
            "retry_count": 0,
            "assessment": None,
            "material": "",
            "task": "",
            "status": LearningStatus.LEARNING.value,
        }


class MockCoachAgent(CoachAgent):
    """Identical to CoachAgent; exists to make the mock nature explicit."""
