from __future__ import annotations

from typing import Any

from nereus.agents.base import BaseAgent
from nereus.core.state import (
    LearningStatus,
    NereusState,
    Roadmap,
    RoadmapTopic,
    Verdict,
)


class TutorAgent(BaseAgent):
    """Tutor Agent.

    Provides learning material and a task for the current roadmap topic. When
    an LLM provider is available the material is generated by the model;
    otherwise deterministic stubs are used. On a ``RETRY`` verdict it produces
    a revision block focused on the reported weak areas.
    """

    def __init__(self, provider=None) -> None:
        self._provider = provider

    # ------------------------------------------------------------------ #
    # Deterministic fallback
    # ------------------------------------------------------------------ #
    def _topic_material(self, topic: RoadmapTopic) -> str:
        return f"Material for '{topic.title}': {topic.description}"

    def _task_for(self, topic: RoadmapTopic) -> str:
        return f"Practical task: demonstrate mastery of '{topic.title}'."

    def _revision_material(self, state: NereusState) -> str:
        assessment = state.get("assessment")
        weak = ", ".join(assessment.weak_areas) if assessment else "the topic"
        return f"Revision material deepening {weak}."

    # ------------------------------------------------------------------ #
    # LLM-backed generation
    # ------------------------------------------------------------------ #
    def _prompt(
        self,
        topic: RoadmapTopic,
        *,
        revision: bool,
        weak_areas: list[str],
    ) -> list[dict[str, Any]]:
        system = (
            "You are a patient tutor. Generate a concise learning material and a "
            "single practical task for the given topic. Return ONLY valid JSON "
            'with keys {"material": "<str>", "task": "<str>"}.'
        )
        if revision:
            instruction = (
                f"The student struggled with: {', '.join(weak_areas)}. "
                "Focus the material on closing these gaps."
            )
        else:
            instruction = "Introduce the topic clearly for the student."
        return [
            {"role": "system", "content": system},
            {
                "role": "user",
                "content": (
                    f"Topic title: {topic.title}\nTopic description: {topic.description}\n"
                    f"{instruction}"
                ),
            },
        ]

    def _generate(
        self,
        topic: RoadmapTopic,
        *,
        revision: bool,
        weak_areas: list[str],
    ) -> tuple[str, str]:
        from nereus.llm.schema import extract_json

        raw = self._provider.complete(
            self._prompt(topic, revision=revision, weak_areas=weak_areas),
            temperature=0.4,
            json_mode=True,
        )
        try:
            data = extract_json(raw)
            return str(data["material"]), str(data["task"])
        except (KeyError, TypeError, ValueError) as exc:
            raise _InvalidTutorResponseError from exc

    # ------------------------------------------------------------------ #
    # Agent interface
    # ------------------------------------------------------------------ #
    def run(self, state: NereusState) -> dict:
        roadmap: Roadmap = state["roadmap"]
        index = state["current_topic_index"]
        topic = roadmap.topics[index]
        assessment = state.get("assessment")
        retrying = assessment is not None and assessment.verdict == Verdict.RETRY
        weak_areas = assessment.weak_areas if assessment else []

        if self._provider is not None:
            try:
                material, task = self._generate(
                    topic, revision=retrying, weak_areas=weak_areas
                )
                return {
                    "material": material,
                    "task": task,
                    "status": LearningStatus.EXAMINING.value,
                }
            except _InvalidTutorResponseError:
                return {
                    "material": (
                        self._revision_material(state)
                        if retrying
                        else self._topic_material(topic)
                    ),
                    "task": self._task_for(topic),
                    "status": LearningStatus.EXAMINING.value,
                }

        material = self._revision_material(state) if retrying else self._topic_material(topic)
        task = self._task_for(topic)
        return {
            "material": material,
            "task": task,
            "status": LearningStatus.EXAMINING.value,
        }


class MockTutorAgent(TutorAgent):
    """Identical to TutorAgent; exists to make the mock nature explicit."""


class _InvalidTutorResponseError(Exception):
    pass
